version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandboxapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./config/php/xdebug.ini:/user/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php/error_reporting.ini:/user/local/etc/php/conf.d/error_reporting.ini
  
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile_nginx
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
  
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local